<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Masuk - Selesa Salon</title><link rel="stylesheet" href="{{ asset('css/login.css') }}"></head><body>
<main class="login-layout"><section class="identity"><div class="logo"><span>S</span><div><strong>selesa</strong><small>SALON & WELLNESS</small></div></div><div class="identity-copy"><small>SISTEM OPERASIONAL INTERNAL</small><h1>Kelola salon dengan lebih tenang.</h1><p>Reservasi, pelayanan, stok, transaksi, dan laporan dalam satu tempat.</p></div><p class="address">Jl. Telaga Asmara, Tlogosari Kulon, Semarang</p></section>
<section class="login-panel"><form method="POST" action="{{ route('login.store') }}">@csrf<header><span class="mobile-logo">S</span><h2>Selamat datang</h2><p>Masuk menggunakan akun karyawan Anda.</p></header>
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<label>Masuk sebagai<div class="role-grid">@foreach(['super_admin'=>['SA','Super Admin'],'admin'=>['AD','Admin'],'marketing'=>['MK','Marketing'],'kasir'=>['KS','Kasir']] as $value=>[$icon,$label])<label class="role-option"><input type="radio" name="role" value="{{ $value }}" @checked(old('role','super_admin')===$value)><span><b>{{ $icon }}</b><small>{{ $label }}</small></span></label>@endforeach</div></label>
<label>Email<input type="email" name="email" value="{{ old('email') }}" placeholder="contoh: kasir@gmail.com" required autofocus></label>
<label>Kata sandi<div class="password"><input id="password" type="password" name="password" placeholder="Masukkan kata sandi" required><button type="button" id="toggle-password">Lihat</button></div></label>
<label class="remember"><input type="checkbox" name="remember"> Ingat saya di perangkat ini</label><button class="submit">Masuk ke sistem →</button><p class="help">Hubungi Super Admin jika Anda lupa akun atau kata sandi.</p></form></section></main>
<script>document.getElementById('toggle-password').addEventListener('click',function(){const p=document.getElementById('password');p.type=p.type==='password'?'text':'password';this.textContent=p.type==='password'?'Lihat':'Sembunyikan'})</script></body></html>
